### PR TITLE
Fix unmanaged schema for bindings

### LINKED ISSUE #3094: ArgumentNullException error
### Discussed in https://github.com/realm/realm-dotnet/discussions/3093

<div type='discussions-op-text'>

<sup>Originally posted by **Unreal852** November 13, 2022</sup>
Hello, i'm making an application with AvaloniaUI and i decided to use Realm as my database but when i bind my view to fields that belongs to an IRealmObject it throws ArgumentNullException. I created a separate project to replicate the issue https://github.com/Unreal852/RealmAvalonia
I did not create an issue because i don't know if i'm doing things wrong or not.</div>

### PR DESCRIPTION
**Pull request by papafe**
Added schema for unmanaged generated objects and fixed `RealmObjectTypeDelegator` when used with unmanaged objects

## Description

Fixes #3094 and #3086

##  TODO

* [x] Changelog entry
* [x] Tests (if applicable)

### CODE REVIEW

File: Realm/Realm/DataBinding/RealmObjectTypeDelegator.cs [hunk 1]
```diff
@@ -45,7 +45,18 @@ protected override PropertyInfo GetPropertyImpl(string name, BindingFlags bindin
...
+                }
+
+                return result;
+            }
+
+            // Schema is null only for woven unmanaged objects
+            if (result?.GetCustomAttribute<WovenPropertyAttribute>() != null)
             {
                 return _propertyCache.GetOrAdd(name, n => new WovenPropertyInfo(result));
             }
```
Comment (nirinchev) [inline Realm/Realm/DataBinding/RealmObjectTypeDelegator.cs:62]: All of that is very repetitive :D

Can we rework to something like:

```suggestion
        if (_schema?.Any(p => p.ManagedName == name) == true || result.GetCustomAttribute<WovenPropertyAttribute>() != null)
        {
            return _propertyCache.GetOrAdd(name, n => new WovenPropertyInfo(result));
        }
```

Comment (papafe) [reply Realm/Realm/DataBinding/RealmObjectTypeDelegator.cs:62]: It is repetitive, but it's also slightly more efficient. If `schema != null`, then we don't need to look for the `WovenPropertyAttribute` anyways, as the schema will always have all the necessary info.
What you wrote was my first version, but I thought it would make sense to be a little more efficient with this if we can.

Comment (papafe) [reply Realm/Realm/DataBinding/RealmObjectTypeDelegator.cs:62]: It is repetitive, but it's also slightly more efficient. If schema != null, then we don't need to look for the WovenPropertyAttribute anyway, as the schema will always have all the necessary info.
What you wrote was my first version, but I thought it would make sense to be a little more efficient with this if we can.

Comment (gagik) [reply Realm/Realm/DataBinding/RealmObjectTypeDelegator.cs:62]: I am curious, would the other "or" statements be evaluated if the first one? I would have assumed if the first condition i.e. `_schema?.Any(p => p.ManagedName == name) == true` is true then it would not bother to evaluate others, thus functionally being similar to the more explicit, longer version.

Comment (papafe) [reply Realm/Realm/DataBinding/RealmObjectTypeDelegator.cs:62]: You are correct, if the first condition is true then it would not check the second one. Here the situation is a little different though.
If the schema is not null and the property is found then the second condition is not evaluated and it's all good.
If the schema is not null and the property is not found, then we don't need to check the second condition anyway because we have all the properties in the schema and it will be useless. 
Only if the schema is null we should check the second condition.

Comment (LaPeste) [reply Realm/Realm/DataBinding/RealmObjectTypeDelegator.cs:62]: In C# `&&` and `||` are short-circuiting, so what Nikola suggested is as efficient as the longer version.
If you specifically want to avoid the short-circuiting you need to use `&` and `|`.

**Review by LaPeste — APPROVED** [review]
After being explained the problem, the solution makes sense to me.

File: Realm/Realm/DataBinding/RealmObjectTypeDelegator.cs (hunk 1 above)
Comment (papafe) [reply Realm/Realm/DataBinding/RealmObjectTypeDelegator.cs:62]: That was it! I didn't think about this 😁

**Review by gagik — APPROVED** [review]

**Review by nirinchev — APPROVED** [review]
